### ISSUE TITLE
Mismatch PCB / Schematic

### ISSUE THREAD

**Issue by simon-budig** [fossasia/badgemagic-hardware#11]
When looking at the PCB of my (violet) badge I've noticed that there is a mismatch between the PCB and the kicad schematics.

For me the silkscreen on the PCB shows the markings "KEY1" "IC1" and "C3". It seems that they refer to the three parts (button, voltage regulator, capacitor) to the left of them.

The schematics refer to the voltage regulator as "U2", I suspect this could be changed to "IC1" to match up the labels.

Also, the voltage regulator on my board is marked "665k", which refers to the 3.6V-version of the XC6206 (which also matches the measured voltage on my badge). If that part is the same for the other colors of the badge (not sure about that, different color LEDs might need slightly different voltages) the part number in the schematics could be adjusted to "XC6206P362MR".

**Comment by kienvo** [comment]
Sorry for being late. I forgot to turn on notification for this repo.

For the IC ref, not just IC1 was mismatched but all four ICs. Two of them were missed ref. The two others were "IC1" and "U1", but they don't match up. IMO, ICs shouldn't have two different ref notations in the same schematic, so they were intentionally annotated from left to right. We could drop a short note near the regulator symbol to indicate this is "IC1" on the original PCB, and so the charger.

About the regulator, I've just checked on red, yellow, and green; they are the same "665k". It was my mistake, didn't notice the part number while pulling it out from built-in symbol.
