### ISSUE TITLE
CH583, CH582M or CH582 build in? lsusb reports CH583

### ISSUE THREAD

**Issue by froscon2024** [fossasia/badgemagic-hardware#20]
What chipset is build into the hardware revision @mariobehling brought to froscon 2024? In lsusb/dmesg it reports with the preinstalled firmware to be a CH583.
The parts list is telling to be a CH582M https://github.com/fossasia/badgemagic-hardware?tab=readme-ov-file#parts-list
The firmware page is telling to be a CH582 https://github.com/fossasia/badgemagic-firmware?tab=readme-ov-file#chipset

**Comment by kienvo** [comment]
CH583 is CH583M for short =], the same for CH582. Comparison table from the datasheet:
![image](https://github.com/user-attachments/assets/bf674c5c-0a04-4ccf-95ca-ecf649eefbef)


CH582 and CH583 are almost identical. The difference is the CH583 has an additional SPI and 1.7v min. supply voltage. In most cases, they can be interchangeable.

**Comment by froscon2024** [comment]
Thanks for the information. 
What does your preinstalled OEM closed source firmware say about the build in chipset in lsusb?

**Comment by kienvo** [comment]
Both my USB-C version and Micro-USB version, lsusb said 'CH583', but the chip is CH582.

**Comment by froscon2024** [comment]
I flashed some hours ago on all badges i have the foss firmware. I checked on the chip and it was always WCH labeled CH582M.
